### ISSUE TITLE
Receive `#ERROR# TypeError: Cannot read property 'columns' of null` on run.

### ISSUE THREAD

**Issue by benjamin-hull** [konradpabjan/actions-move-labeled-issue#15]
I'm trying to set up this action on a private repo, and receive the following log on run:

```
Run konradpabjan/move-labeled-or-milestoned-issue@v2.0
This project is configured at the repo level. Repo Owner:[Owner Org], repo name:[Private repo] project number#17
#ERROR# TypeError: Cannot read property 'columns' of null
```

My workflow YAML looks like this:

```yml
on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - name: Move labeled or milestoned issue to a specific project column
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.WORKFLOW_ACTIONS }}"
        project-url: "https://github.com/[Owner]/[Repo]/projects/17"
        column-name: "Needs Info"
        label-name:  "Awaiting more info"
        columns-to-ignore: "Done"
```

The project URL is definitely correct, as are the names of the columns and labels.

This is my first attempt at using actions, so I could be missing something. Any ideas? Thanks in advance!
